# StartOS 0.4.x Build Service Workflow
#
# Drop this file into .github/workflows/ in your StartOS package repository
# to enable CI builds on every commit and pull request.
#
# Requirements:
# - Your repository must have a Makefile with a default target that builds the .s9pk
# - The manifest must be at startos/manifest.ts (StartOS 0.4.x standard)

name: Build Service

on:
  workflow_dispatch:
  pull_request:
    paths-ignore: ["*.md"]
    branches: ["main", "master"]
  push:
    paths-ignore: ["*.md"]
    branches: ["main", "master"]

jobs:
  BuildPackage:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare StartOS SDK
        uses: jeffreymsimon/start9-build_wrapper@main

      - name: Checkout services repository
        uses: actions/checkout@v4

      - name: Install npm dependencies
        run: npm ci

      - name: Build the service package
        id: build
        run: |
          git submodule update --init --recursive
          make
          # Extract package ID from the built .s9pk file
          S9PK=$(ls -t *.s9pk 2>/dev/null | head -1)
          if [ -z "$S9PK" ]; then
            echo "Error: No .s9pk file found after build"
            exit 1
          fi
          PACKAGE_ID=$(start-cli s9pk inspect "$S9PK" manifest | jq -r '.id')
          echo "package_id=$PACKAGE_ID" >> $GITHUB_ENV
          printf "\n SHA256SUM: $(sha256sum ${S9PK}) \n"
        shell: bash

      - name: Upload .s9pk
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.package_id }}.s9pk
          path: ./*.s9pk
